### ISSUE TITLE
angle brackets inside of absolute values don't get displayed properly

### ISSUE THREAD

**Issue by xlf1024** [runarberg/mathup#8]
`| (: a, b :) |`  renders to |〈a,b|)| instead of |〈a,b〉|.
(Enter `| {: (: a,b :) :} |` to get an optically correct result)

**Comment by runarberg** [comment]
Correct: I'll look at this when I have time. You can also simply type ` |〈a,b〉|` for correct result.

**Comment by runarberg** [comment]
This will be fixed in the next major version (named *“mathup”* #36) which is a complete rewrite of the internals.

However *mathup* will also introduce a new piped fence open input `|(` and `)|`, this is in addition to `abs((:a, b:))` which is currently available. In short, in the next version, `| (: a, b :) |`, `|((: a, b :))|`, and `abs((: a, b :))` should all work. However `|(: a, b :)|` will not (but `\|(: a, b :)|` will).

**Comment by runarberg** [comment]
Also `|<<a/b>>|` works since mathup 1.0.0-alpha.3
